services:
  kagome_front:
    build: git@github.com:notoiro/kagome_front.git
  replace_http:
    build: git@github.com:notoiro/replace_http.git
  voicevox:
    image: voicevox/voicevox_engine
  sharevox:
    image: sharevox/sharevox_engine
  kana:
    build: .
