services:
  kagome_front:
    build: https://github.com/notoiro/kagome_front.git
  replace_http:
    build: https://github.com/notoiro/replace_http.git
  voicevox:
    image: voicevox/voicevox_engine:cpu-ubuntu20.04-latest
    healthcheck:
      test: curl http://localhost:50021/speakers || exit 1
      start_period: "2s"
  kana:
    build: .
    command: sh -c "sleep 30 && cd /app && npm run production"
    depends_on:
      - kagome_front
      - replace_http
      - voicevox
