services:
  kagome_front:
    build: https://github.com/notoiro/kagome_front.git
  replace_http:
    build: https://github.com/notoiro/replace_http.git
  voicevox:
    image: voicevox/voicevox_engine:cpu-ubuntu20.04-latest
    healthcheck:
      # prettier-ignore
      test: ['CMD-SHELL',"curl localhost:50021 | grep -q 'Not Found' || exit 1"]
  kana:
    build: .
    depends_on:
      - kagome_front
      - replace_http
      - voicevox
