services:
  kagome_front:
    build: https://github.com/notoiro/kagome_front.git
  replace_http:
    build: https://github.com/notoiro/replace_http.git
  voicevox:
    image: voicevox/voicevox_engine:cpu-ubuntu20.04-latest
  sharevox:
    image: sharevox/sharevox_engine:cpu-ubuntu20.04-latest
  kana:
    build: .
    depends_on:
      - kagome_front
      - replace_http
      - voicevox
      - sharevox
